name: Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Update packages and install Docker if not installed
          sudo yum update -y
          sudo yum install -y docker
          
          # Start Docker service
          sudo service docker start
          
          # Pull the latest Docker image from Docker Hub
          sudo docker pull kasunmadhuwantha/2560526b8f1c:latest
          
          # Check if the running container is using the latest image
          current_image=$(sudo docker inspect --format='{{.Config.Image}}' 2560526b8f1c 2>/dev/null || echo "none")
          latest_image="kasunmadhuwantha/2560526b8f1c:latest"
          
          if [ "$current_image" != "$latest_image" ]; then
            echo "Updating container..."
            # Stop and remove the existing container if it exists
            sudo docker stop 2560526b8f1c || true
            sudo docker rm 2560526b8f1c || true
            
            # Run the new Docker container
            sudo docker run -d --name 2560526b8f1c -p 80:80 $latest_image
          else
            echo "Container is already using the latest image. No action needed."
          fi
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
